name: Send Visa Email

on:
  push:
    branches:
      - main     # Run whenever a commit is pushed to the main branch
  schedule:
    - cron: "0 13 * * *"   # Runs daily at 7:00 PM Bangladesh time (UTC+6)
  workflow_dispatch:       # Allow manual run from Actions tab
  
jobs:
  send-email:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell Email Script
        shell: pwsh
        run: ./send-email.ps1

